#!/usr/bin/env python3
"""Generates dynalm/src/tokenizer/unicode_tables.inc from Python's unicodedata.

Emits sorted, merged code-point ranges for the categories the pre-tokenizers
need: letters (\\p{L}), numbers (\\p{N}) and White_Space (\\s).

    PYTHONUTF8=1 python tools/gen_unicode_tables.py > dynalm/src/tokenizer/unicode_tables.inc
"""
import sys
import unicodedata

# Unicode White_Space property (PropList.txt); regex \s in the Rust regex /
# Oniguruma engines used by HF tokenizers matches exactly this set.
WHITE_SPACE = [
    (0x0009, 0x000D), (0x0020, 0x0020), (0x0085, 0x0085), (0x00A0, 0x00A0),
    (0x1680, 0x1680), (0x2000, 0x200A), (0x2028, 0x2029), (0x202F, 0x202F),
    (0x205F, 0x205F), (0x3000, 0x3000),
]


def ranges(pred):
    out = []
    start = None
    for cp in range(0x110000):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, rs):
    print(f"// {len(rs)} ranges")
    print(f"inline constexpr CodepointRange {name}[] = {{")
    line = "   "
    for a, b in rs:
        item = f" {{0x{a:X}, 0x{b:X}}},"
        if len(line) + len(item) > 98:
            print(line)
            line = "   "
        line += item
    print(line)
    print("};\n")


def main():
    cat = lambda cp: unicodedata.category(chr(cp))
    print(f"// Generated by tools/gen_unicode_tables.py from Unicode {unicodedata.unidata_version}.")
    print("// Do not edit.\n")
    emit("kLetterRanges", ranges(lambda cp: cat(cp).startswith("L")))
    emit("kNumberRanges", ranges(lambda cp: cat(cp).startswith("N")))
    emit("kWhitespaceRanges", WHITE_SPACE)


if __name__ == "__main__":
    sys.exit(main())
